name: kafka_protocol
description: Implementation of the Kafka protocol in Dart.
version: 0.1.0
homepage: https://github.com/Blimster/kafka_protocol
publish_to: none

environment:
    sdk: ">=2.16.0 <3.0.0"

dependencies: 
    uuid: ^3.0.0

dev_dependencies:
    pedantic: ^1.9.0
    test: ^1.20.0
